######################
# Alacritty's Config #
######################

[general]
live_config_reload = true

[terminal]
shell = "/bin/bash"

[window]
opacity = 0.95
decorations = "None"
startup_mode = "Maximized"

[font]
size = 12
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }

[keyboard]
bindings = [
  { key = "v", mods = "Control", mode = "AppCursor|~Vi", action = "Paste" },
]
