######################
# Alacritty's Config #
######################

[general]
live_config_reload = true

[terminal]
shell = "/bin/bash"

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
size = 12

[keyboard]
bindings = [
  { key = "v", mods = "Control", mode = "AppCursor|~Vi", action = "Paste" },
]
